### ISSUE TITLE
no working nick and leaderbord

### ISSUE THREAD

**Issue by mafiakb** [Fan7asy/Client#1]
how fix ?

![image](https://user-images.githubusercontent.com/12769609/31048626-e470d316-a5e6-11e7-82d8-9f39001913e5.png)
![image](https://user-images.githubusercontent.com/12769609/31048628-ec7021ac-a5e6-11e7-9fda-71c778e8771e.png)

**Comment by Fan7asy** [comment]
What server are you using may I know?

**Comment by Fan7asy** [comment]
Doesn't matter I must've screwed something up in one of my commits.

**Comment by mafiakb** [comment]
yes, i test your server https://github.com/Fan7asy/Cells

**Comment by Fan7asy** [comment]
Oh sorry that may be the issue, the server doesn't send the leaderboard yet :D

**Comment by Fan7asy** [comment]
And the nick shows up past 200 mass to avoid lag

**Comment by mafiakb** [comment]
I wait for the server update?

**Comment by Fan7asy** [comment]
Yeah, I'll try to put one out soon :)

**Comment by mafiakb** [comment]
ok :D ty ;)
