### ISSUE TITLE
how change leaderboard in html

### ISSUE THREAD

**Issue by mafiakb** [Fan7asy/Client#14]
how add leaderboard here ```<span id="leader"><li></li></span>```
 pleaseeee

**Comment by Fan7asy** [comment]
Please explain

**Comment by mafiakb** [comment]
draw leaderboard in html css and append how agarplus

**Comment by mafiakb** [comment]
is possible?

**Comment by Fan7asy** [comment]
Yes it is.
Just create an element that you'd like to append to and use the leaderboard loop to append to it.

**Comment by mafiakb** [comment]
Any example please

**Comment by CodeFlush** [comment]
Look @Fan7asy , Not everyone is as good, talented or skilled like you. If he knew how to do it he would of done it himself. He's asking you for the code.

**Comment by mafiakb** [comment]
@CodeFlush hi, u can help me?

**Comment by Fan7asy** [comment]
@CodeFlush I completely understand that, but you have to understand that I only provide the project. It is my responsibility to make sure everything works. This repo is like a template for the user to expand on, instead of stealing other's work and calling it theirs. Like a lot of agar clones do.

**Comment by Fan7asy** [comment]
Learning to code isn't hard with the right resources. I've been coding since I was 12 (now 14) and I've never found it difficult to understand.

**Comment by Fan7asy** [comment]
Also I failed to mention that this would generate a lot of lag.

**Comment by mafiakb** [comment]
@Fan7asy but any example? please

**Comment by Fan7asy** [comment]
Look through the agarplus client.
