### ISSUE TITLE
Let me use chat. please.

### ISSUE THREAD

**Issue by shift710** [Fan7asy/Client#2]
Good morning. I like this client very much, I want to use some features and chat on this client. I hope you update soon! (I'm sorry that English is bad for Korea, but I want to try your thing)

**Comment by Fan7asy** [comment]
Morning, I am implementing a chat as we speak 🙂 @shift710

**Comment by Fan7asy** [comment]
I'll be updating it very soon

**Comment by shift710** [comment]
Thank you very much for trying the update!

**Comment by shift710** [comment]
Is it possible to chat like a cigar? I would like to add chat toast as much as possible.

**Comment by Fan7asy** [comment]
Explain please

**Comment by shift710** [comment]
Let the chat go down like cigar, chat toast is like https://github.com/nobabo/rugar!

**Comment by Fan7asy** [comment]
I'm sorry I cannot really help with that.

**Comment by shift710** [comment]
I'm sorry for that! The current spectator function is not working properly. Also add a lot of features like cigar client.
+ IP: I would like to remove the window asking for port

**Comment by Fan7asy** [comment]
I don't want this client to be like cigar, I want it to be as fast and clean as possible.

To remove the prompt, please remove this snippet that starts at line 62 of `main.js`:

```JS
$(document).ready(function () {
    connect(request, true);
});
```

Then you may use the ```connect``` function:

```JS
connect("ServerIP");
```

> I will fix the `watch` / `spectate` function shortly.

**Comment by shift710** [comment]
62 Are you clearing the line and putting the connect function in place? If it is correct, this function does not seem to work.

**Comment by Fan7asy** [comment]
Just remove the lines that snippet that I gave you.

**Comment by Fan7asy** [comment]
After, replace it with the code I gave you.

**Comment by shift710** [comment]
Thank you. I succeeded. work hard! If only the watch function is patched, this client is a perfect client!

**Comment by Fan7asy** [comment]
Thank you, I have just fixed the `watch` function, so you may want to update your code, also I appreciate the support 🙂

**Comment by mafiakb** [comment]
fan7asy i need ur skype please sorry for open thread :(

**Comment by Fan7asy** [comment]
I do not use Skype, but feel free to add me on Discord: Fan7asy#7438
