### ISSUE TITLE
FeaTURES

### ISSUE THREAD

**Issue by AlexHGaming** [Fan7asy/Client#9]
Ye if you like add a custom server list then I will re-promote your game on my site & give dank memes & give you a special role on my dISCORD SERVER
awww special

**Comment by AlexHGaming** [comment]
@Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy @Fan7asy

**Comment by Fan7asy** [comment]
Fine
